Домашнее задание №7 Указатели + Строки
bugslayer312/StudentHomeworks pull request #5
Opened 2017-05-02 11:57 UTC by leshkov1980

Домашнее задание №7 Указатели + Строки

2017-05-04 21:15 UTC, bugslayer312 requested changes
Сохраните h/cpp файлы в другой кодировке (UTF-8) например. А то вместо русских символов иероглифы. http://imgdepo.com/id/10606403.jpg

2017-05-04 21:18 UTC, bugslayer312 requested changes

2017-05-04 21:18 UTC, bugslayer312 commented on LeshkovAV/Leshkov/Leshkov/Ukazateli.cpp
> +	//1. ���������� ������� ������ ������ ���������� ���������� �������,
Сохранить в UTF-8 чтобы не было такого.

2017-05-07 20:36 UTC, bugslayer312 requested changes

2017-05-07 20:36 UTC, bugslayer312 commented on LeshkovAV/Leshkov/Leshkov/List.cpp
> +	for (int i = 0; i < size; i++, ptr++)
Здесь и далее используйте какую-нибудь одну форму перебора массива: либо доступ по индексу с инкрементом индекса
for (int i = 0; i < size; ++i) {
  ptr[i] = rand() % width + begin;
}
Либо через указатель и инкремент указателя
for (int *p = ptr, *end = ptr + size; p != end; ++p) {
  *p = rand() % width + begin;
}
А то у вас смешивается инкремент счетчика и инкремент указателя.

2017-05-07 20:36 UTC, bugslayer312 commented on LeshkovAV/Leshkov/Leshkov/Ukazateli.cpp
> +	case 2:
У вас case 1 и case 2 отличаются только одной строчкой с условием, остальное одинаковое.
Может написать сложное условие, включив туда vybor, и объединить два блока, чтобы не повторялось одно и то же ?

2017-05-07 20:36 UTC, bugslayer312 commented on LeshkovAV/Leshkov/Leshkov/List.cpp
> +			*mass_nElem += 1;
можно дальше не проверять меньше и больше нуля раз он равен нулю. continue ?

2017-05-07 20:36 UTC, bugslayer312 commented on LeshkovAV/Leshkov/Leshkov/List.cpp
> +			*(mass_nElem + 1) += 1;
можно дальше не проверять на больше нуля раз он равен нулю. continue ?

2017-05-07 20:36 UTC, bugslayer312 commented on LeshkovAV/Leshkov/Leshkov/List.cpp
> +		if (*(ptr + i) > 0) {
если мы попали в какое-то из двух условий выше и продолжили через continue, то сюда мы попадем только в единственном случае (больше нуля) и проверку на больше можно опустить

2017-05-07 20:36 UTC, bugslayer312 commented on LeshkovAV/Leshkov/Leshkov/Ukazateli.cpp
> +	int *ptr_mass = static_mass;
В чем смысл объявления ptr_mass ? Почему нельзя сразу передать static_mass в SortMassiv() ?

2017-05-07 20:36 UTC, bugslayer312 commented on LeshkovAV/Stroki/Stroki/Source.cpp
> +char *DeleteOneChar(char *str1, char *str2, size_t numElem)
не понятно из объявления, который из параметров результат. Обычно принято выходные параметры располагать в конце списка. Если входная строка str2 не планирует меняться, то добавить const.
char *DeleteOneChar(const char *inputStr, size_t nInput, char *outputStr);

2017-05-07 20:36 UTC, bugslayer312 commented on LeshkovAV/Stroki/Stroki/Source.cpp
> +	for (size_t i = numElem - 1; *(str2 + i) != '\0'; ++i)
А зачем цикл перебирать ? Может проще тоже скопировать оставшееся ?
strcpy(str1 + numElem - 1, str2 + numElem);

2017-05-07 20:36 UTC, bugslayer312 commented on LeshkovAV/Stroki/Stroki/Source.cpp
> +char *DeleteChar(char *str1, char *str2, char sym)
То же, что и для DeleteOneChar.

2017-05-07 20:36 UTC, bugslayer312 commented on LeshkovAV/Stroki/Stroki/Source.cpp
> +			*p_str1--;
прибавить p_str1 в скобке for, чтобы потом убавить его тут. может убрать оттуда и написать что-то вроде этого 
if (*p_str2 != sym)
  *p_str1++ = *p_str2;

2017-05-07 20:36 UTC, bugslayer312 commented on LeshkovAV/Stroki/Stroki/Source.cpp
> +	for (size_t i = numPoz; *(str + i) != '\0'; ++i, ++tmpnext)
Можно сдвигать остаток, идя с конца, и обойтись без временной переменной.

2017-05-07 20:36 UTC, bugslayer312 commented on LeshkovAV/Stroki/Stroki/Stroki.cpp
> +	}
так должно быть быстрее
while (p = strchr(p, '.'))
{
	*p = '!';
}

2017-05-07 20:36 UTC, bugslayer312 commented on LeshkovAV/Stroki/Stroki/Stroki.cpp
> +	}
Можно так же воспользоваться strchr()
while (p = strchr(p, sym))
{
++count;
}

2017-05-07 20:36 UTC, bugslayer312 commented on LeshkovAV/Stroki/Stroki/Stroki.cpp
> +		if (64 < (int)*p && (int)*p < 91 || 96 < (int)*p && (int)*p < 123)
isalpha(*p)

2017-05-07 20:36 UTC, bugslayer312 commented on LeshkovAV/Stroki/Stroki/Stroki.cpp
> +		if (47 < (int)*p && (int)*p < 58)
isdigit(*p)

2017-05-07 20:36 UTC, bugslayer312 commented on LeshkovAV/Stroki/Stroki/Stroki.cpp
> +		if (31 < (int)*p && (int)*p < 48 || 57 < (int)*p && (int)*p < 65 || 90 < (int)*p && (int)*p < 97 || 122 < (int)*p && (int)*p < 127)
isprint(*p)

2017-05-07 20:36 UTC, bugslayer312 commented on LeshkovAV/Stroki/Stroki/Source.cpp
> +			polindrm = true;
polindrm = true; лишнее
можно один раз при инициализации присвоить true

2017-05-10 18:55 UTC, leshkov1980 commented on LeshkovAV/Stroki/Stroki/Source.cpp
> +char *DeleteOneChar(char *str1, char *str2, size_t numElem)
Делал по аналогии со строковыми функциями. Там обычно возвращает первую строку. Такого нюанса в оформлении функций нам, к сожалению не давали.

2017-05-10 18:57 UTC, leshkov1980 commented on LeshkovAV/Stroki/Stroki/Source.cpp
> +char *DeleteOneChar(char *str1, char *str2, size_t numElem)
Учту на будущее

2017-05-10 19:07 UTC, leshkov1980 commented on LeshkovAV/Leshkov/Leshkov/Ukazateli.cpp
> +	case 2:
Было множество мыслей по этой реализации. Большое спасибо за идею.

2017-05-10 19:29 UTC, leshkov1980 commented on LeshkovAV/Stroki/Stroki/Stroki.cpp
> +		if (47 < (int)*p && (int)*p < 58)
я использовал эту функцию в следующем задании. 
А именно здесь задание звучало: Достаточно сравнить код символа с диапазоном кодов цифр. Код символа 0 – 48, 1 – 49, 2 – 50 …. 9 – 57.
И я так понимаю его и нужно было выполнить сравнивая коды символов.

2017-05-10 19:53 UTC, leshkov1980 commented on LeshkovAV/Stroki/Stroki/Source.cpp
> +	for (size_t i = numPoz; *(str + i) != '\0'; ++i, ++tmpnext)
Спасибо, за хорошую идею.

2017-05-10 20:02 UTC, leshkov1980 commented on LeshkovAV/Stroki/Stroki/Stroki.cpp
> +	}
Логично, если не находит, то возвращает НУЛЬ

2017-05-10 20:31 UTC, leshkov1980 commented on LeshkovAV/Stroki/Stroki/Stroki.cpp
> +	}
здесь нужно добавить в теле цикла смещение указателя р.
Иначе получается бесконечный цикл.
while (p = strchr(p, sym))
	{
		++count;
		++p;
	}

2017-05-21 05:11 UTC, bugslayer312 approved these changes

2017-05-21 05:11 UTC, merged