Дамашнее задание: односвязный список
bugslayer312/StudentHomeworks pull request #9
Opened 2017-05-06 15:03 UTC by Romannaymchikys

задание 1 - 3

2017-05-07 17:31 UTC, bugslayer312 requested changes

2017-05-07 17:31 UTC, bugslayer312 commented on Naymchik R.М/HomeWork1/HomeWork1/Data.cpp
> +	strncpy(result->Name, name, 20);
Учитывать символ конца строки. Если буффер объявлен размером 20 символов, то скопировать туда можно только 19.

2017-05-07 17:31 UTC, bugslayer312 commented on Naymchik R.М/HomeWork1/HomeWork1/Stack.cpp
> +}
Что этот файл делает в домашнем задании по спискам ?

2017-05-07 17:31 UTC, bugslayer312 commented on Naymchik R.М/HomeWork1/HomeWork1/Stack.h
> +bool IsEmpty(const struct Stack* stack);
Что этот файл делает в домашнем задании по спискам ?

2017-05-07 17:31 UTC, bugslayer312 commented on Naymchik R.М/HomeWork1/HomeWork1/HomeWork1.cpp
> +		return  strchr(data->Name, 77);
1. Не используйте магические числа. 77 ? Если это символ М, то просто передавайте его в функцию strchr(data->Name, 'M'). 'M' - это тип char, char приводится к int без проблем.
2. У вас FindSymbol возвращает bool, а strchr возвращает char* – не соответствие типов. Если вам нужно вернуть булевое значение, сделайте это явно
return strchr(data->Name, 'M') != NULL;

2017-05-07 17:31 UTC, bugslayer312 commented on Naymchik R.М/HomeWork1/HomeWork1/HomeWork1.cpp
> +	bool ComparNode(const struct Data* data1, const struct Data* data2)
Название должно точно отражать то, что делает функция - CompareNodeBySalary сравнить узлы по зарплате

2017-05-07 17:31 UTC, bugslayer312 commented on Naymchik R.М/HomeWork1/HomeWork1/HomeWork1.cpp
> +			return -1;
Почему -1 ? функция возвращает bool а не int.

2017-05-07 17:31 UTC, bugslayer312 commented on Naymchik R.М/HomeWork1/HomeWork1/HomeWork1.cpp
> +		if (data1->Salary == data2->Salary)
Если вам нужно вернуть true, если первое значение не больше второго, можно написать просто
return data1->Salary <= data2->Salary;
Это все тело данной функции.

2017-05-07 17:31 UTC, bugslayer312 commented on Naymchik R.М/HomeWork1/HomeWork1/List.cpp
> +			free(p);
free(p) повторяется в обеих ветках. Может совместить и поместить после free(p->ListData) ?

2017-05-07 17:31 UTC, bugslayer312 commented on Naymchik R.М/HomeWork1/HomeWork1/List.cpp
> +ListNode* FreeMemory(ListNode* newfirst ,size_t& counter)
size_t& counter
В языке С нет ссылок

2017-05-07 17:31 UTC, bugslayer312 commented on Naymchik R.М/HomeWork1/HomeWork1/List.cpp
> +	return 0;
Зачем нужно возвращаемое значение типа ListNode*, если функция всегда возвращает 0 ?

2017-05-07 17:31 UTC, bugslayer312 commented on Naymchik R.М/HomeWork1/HomeWork1/List.cpp
> +			newp1 = newp1->Next;
newp1 = newp1->Next; повторяется в обеих ветках. Объединить и вынести из if.

2017-05-07 17:31 UTC, bugslayer312 commented on Naymchik R.М/HomeWork1/HomeWork1/List.cpp
> +		p = p->Next;
p = p->Next нужно делать после копирования указателя на данные из старого списка в новый. Иначе первый узел будет пропущен.

2017-05-07 17:31 UTC, bugslayer312 commented on Naymchik R.М/HomeWork1/HomeWork1/List.cpp
> +	char NameTmp[20];
В struct Data строки заданы статически, можно просто использовать обычное присваивание, чтобы поменять значения двух структур.
struct Data tmp = *(node1->ListData);
*(node1->ListData) = *(node2->ListData);
*(node2->ListData) = tmp;

А лучше даже просто обменять указатели на данные в узлах
struct Data* tmp = node1->ListData;
node1->ListData = node2->ListData;
node2->ListData = tmp;

2017-05-07 17:31 UTC, bugslayer312 commented on Naymchik R.М/HomeWork1/HomeWork1/List.cpp
> +	selector = false;
Не используйте глобальную переменную таким образом. Вы объявляете ее глобально со значением true. Затем внутри какой-то функции вызывается другая функция, а еще внутри нее переменная меняется на false. Это очень плохой дизайн. А если потом изменится порядок вызова функций и место, откуда эта переменная меняется потеряется ? Не следует вообще использовать глобальные переменные, если без них только совсем никак. В данном случае, можно параметр передавать среди аргументов функции.

2017-05-07 17:31 UTC, bugslayer312 commented on Naymchik R.М/HomeWork1/HomeWork1/List.cpp
> +	PrintList(newfirst);
У вас функция называется УдалитьВсе, а не УдалитьВсеИНапечататьСписок. В функцию стоит помещать лишь то, что она делает. Остальное делать снаружи.

2017-05-07 17:31 UTC, bugslayer312 commented on Naymchik R.М/HomeWork1/HomeWork1/List.cpp
> +	PrintList(newfirst);
То же самое, что и в RemoveAll(). Это лишнее здесь.

2017-05-07 17:31 UTC, bugslayer312 commented on Naymchik R.М/HomeWork1/HomeWork1/List.cpp
> +	PrintList(first);
То же самое, что и в RemoveAll(). Это лишнее здесь.

2017-05-07 17:31 UTC, bugslayer312 commented on Naymchik R.М/HomeWork1/HomeWork1/List.cpp
> +ListNode* GreateNewfirst(ListNode* newfirst, ListNode* first)
1. Если функция создает копию списка, нужно так и назвать CreateListCopy
2. Вершину нового списка лучше создать в этой функции а не передавать снаружи, тем более что память под остальные узлы также выделяется здесь.

2017-05-07 17:31 UTC, bugslayer312 commented on Naymchik R.М/HomeWork1/HomeWork1/List.cpp
> +	return 0;
Очень замудренная логика функции и сложно разобраться, что она делает. С трудом можно наверное догадаться что она оставляет не больше count элементов с начала списка. Надо переделать на что-то другое и места где она используется.

2017-05-07 17:31 UTC, bugslayer312 commented on Naymchik R.М/HomeWork1/HomeWork1/List.cpp
> +		Swap(newp2, newp3);
Подразумевалось, что нужно поменять ссылки между узлами, а не через обмен содержимого узлов. Наверное, мой недочет, надо было написать в задании. Но я говорил об этом, когда его давал.
Через апдейт ссылок между узлами это получается в один проход по списку очень просто.

2017-05-07 17:31 UTC, bugslayer312 commented on Naymchik R.М/HomeWork1/HomeWork1/List.cpp
> +ListNode* RemoveAll(ListNode* first, DataCompareFunc predicate)
Как-то очень запутанно и переусложнено. Можно ведь проще. В цикле пройти всего один раз, имея указатель на предыдущий, текущий и последующий элемент. Если текущий элемент надо удалить, то обновить ссылки с предыдущего на последующий и удалить текущий узел. Отдельное внимание уделить ситуации, когда удаляется первый элемент списка.

2017-05-27 19:33 UTC, bugslayer312 requested changes

2017-05-27 19:33 UTC, bugslayer312 commented on Naymchik R.М/HomeWork1/HomeWork1/List.cpp
> +	struct ListNode* newNode3 = first->Next->Next;
Если в списке меньше двух элементов (1 или 0), то программа завершится аварийно.

2017-05-28 17:38 UTC, Romannaymchikys commented
я исправил задание
https://github.com/bugslayer312/StudentHomeworks/pull/9/commits/324dd286a0869e4045693befef5bffd9d1e05b76
а остальные исправление по ссылке:
https://github.com/bugslayer312/StudentHomeworks/pull/9/commits/999adc2ad1950ad8bbd2a6f63cfb30fe751d1dd9

2017-05-27 21:33 GMT+02:00 Eugene Moskalev <notifications@github.com>:

> *@bugslayer312* requested changes on this pull request.
> ------------------------------
>
> In Naymchik R.М/HomeWork1/HomeWork1/List.cpp
> <https://github.com/bugslayer312/StudentHomeworks/pull/9#discussion_r118827550>
> :
>
> > @@ -147,20 +147,24 @@ ListNode* RemoveAll(ListNode* newfirst, DataCompareFunc predicate)
>  ListNode* Revertl(ListNode* first)
>  {
>  	struct ListNode* newNode1 = first;
> -	struct ListNode* newNode2 = first;
> -	
> -	for (size_t takt = 1, counter = GetCount(first), max = (int)(counter / 2); takt <= max; takt++)
> -	{
> -		newNode2 = first;
> -		for (size_t max2 = counter - takt; max2; --max2)
> -		{
> -			newNode2 = newNode2->Next;
> -		}
> -		Swap(newNode1, newNode2);
> -		newNode1 = newNode1->Next;
> +	struct ListNode* newNode2 = first->Next;
> +	struct ListNode* newNode3 = first->Next->Next;
>
> Если в списке меньше двух элементов (1 или 0), то программа завершится
> аварийно.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bugslayer312/StudentHomeworks/pull/9#pullrequestreview-40659191>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AYrdinUO8go97zavwZjNngdljxbcqbMjks5r-Hp-gaJpZM4NSy3O>
> .
>

2017-05-30 16:10 UTC, bugslayer312 approved these changes

2017-05-30 16:10 UTC, merged